def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        
        # Provide explicit name for the index
        batch_op.create_index('ix_log_ip', ['ip'], unique=False)
        
        # Provide explicit name for the foreign key constraint
        batch_op.create_foreign_key('fk_log_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('log', schema=None) as batch_op:
        # Drop the foreign key constraint and provide the constraint name
        batch_op.drop_constraint('fk_log_user', type_='foreignkey')
        
        # Drop the index and provide the index name
        batch_op.drop_index('ix_log_ip')
        
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
