"""Initial migration

Revision ID: ce8f0b830c1d
Revises: 
Create Date: 2025-04-10 14:47:04.090451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8f0b830c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('uq_user_api_key', ['api_key'])  # Fixed the issue here

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_api_key', type_='unique')  # Fixed the issue here
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
